version: '3.3'
services:
  dev:
    container_name: aluxion_backend_test
    image: aluxion_backend_test:1.0.0
    ports:
    - 3000:3000
    - 3001:9229
    build:
      context: .
      dockerfile: ./Dockerfile
      command: npm run start:dev
    networks:
      - aluxion-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - aluxion-network
    restart: always
  